apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
      - name: order-deployment
        image: service_order:0.1
        ports:
        - containerPort: 8080

